#!/usr/bin/python3

import datetime

today = datetime.date.today()

f = open('inc/etk/version.h', 'w')


f.write("""
#ifndef ETK_AUTOVERSION_H_INCLUDED
#define ETK_AUTOVERSION_H_INCLUDED

namespace etk
{

namespace Version
{
""")

f.write("	inline const char* get_year() { return \"")
f.write(str(today.year))
f.write("\"; }\n")

f.write("	inline const char* get_month() { return \"")
f.write('{0:02d}'.format(today.month))
f.write("\"; }\n")

f.write("	inline const char* get_day() { return  \"")
f.write('{0:02d}'.format(today.day))
f.write("\"; }\n")

f.write("	inline const char* get_version() { return \"")
f.write('{0:02d}'.format(today.year))
f.write('{0:02d}'.format(today.month))
f.write('{0:02d}'.format(today.day))
f.write("\"; }\n")

f.write("""
}

}

#endif
""")
	
	
f.close()

