/** Generated by ETK Unit Conversion Generator script. */

#ifndef ETK_CONVERSIONS_H
#define ETK_CONVERSIONS_H

namespace etk
{

inline float thou_to_meters(float in) { return in*2.5399986284e-05f; }
inline float inches_to_meters(float in) { return in*0.025399986284f; }
inline float feet_to_meters(float in) { return in*0.304799990246f; }
inline float yards_to_meters(float in) { return in*0.914402757839f; }
inline float miles_to_meters(float in) { return in*1609.34449789f; }
inline float naut_miles_to_meters(float in) { return in*1851.99932587f; }
inline float centimeters_to_meters(float in) { return in*0.01f; }
inline float millimeters_to_meters(float in) { return in*0.001f; }
inline float kilometers_to_meters(float in) { return in*1000.0f; }

inline float meters_to_thou(float in) { return in*39370.1f; }
inline float inches_to_thou(float in) { return in*1000.0f; }
inline float feet_to_thou(float in) { return in*12000.006096f; }
inline float yards_to_thou(float in) { return in*36000.1280164f; }
inline float miles_to_thou(float in) { return in*63360053.8165f; }
inline float naut_miles_to_thou(float in) { return in*72913398.6595f; }
inline float centimeters_to_thou(float in) { return in*393.701f; }
inline float millimeters_to_thou(float in) { return in*39.3701f; }
inline float kilometers_to_thou(float in) { return in*39370100.0f; }

inline float meters_to_inches(float in) { return in*39.3701f; }
inline float thou_to_inches(float in) { return in*0.001f; }
inline float feet_to_inches(float in) { return in*12.000006096f; }
inline float yards_to_inches(float in) { return in*36.0001280164f; }
inline float miles_to_inches(float in) { return in*63360.0538165f; }
inline float naut_miles_to_inches(float in) { return in*72913.3986595f; }
inline float centimeters_to_inches(float in) { return in*0.393701f; }
inline float millimeters_to_inches(float in) { return in*0.0393701f; }
inline float kilometers_to_inches(float in) { return in*39370.1f; }

inline float meters_to_feet(float in) { return in*3.28084f; }
inline float thou_to_feet(float in) { return in*8.3333291e-05f; }
inline float inches_to_feet(float in) { return in*0.083333291f; }
inline float yards_to_feet(float in) { return in*3.00000914403f; }
inline float miles_to_feet(float in) { return in*5280.00180247f; }
inline float naut_miles_to_feet(float in) { return in*6076.11346829f; }
inline float centimeters_to_feet(float in) { return in*0.0328084f; }
inline float millimeters_to_feet(float in) { return in*0.00328084f; }
inline float kilometers_to_feet(float in) { return in*3280.84f; }

inline float meters_to_yards(float in) { return in*1.09361f; }
inline float thou_to_yards(float in) { return in*2.77776790001e-05f; }
inline float inches_to_yards(float in) { return in*0.0277776790001f; }
inline float feet_to_yards(float in) { return in*0.333332317333f; }
inline float miles_to_yards(float in) { return in*1759.99523634f; }
inline float naut_miles_to_yards(float in) { return in*2025.36498277f; }
inline float centimeters_to_yards(float in) { return in*0.0109361f; }
inline float millimeters_to_yards(float in) { return in*0.00109361f; }
inline float kilometers_to_yards(float in) { return in*1093.61f; }

inline float meters_to_miles(float in) { return in*0.000621371f; }
inline float thou_to_miles(float in) { return in*1.57828148773e-08f; }
inline float inches_to_miles(float in) { return in*1.57828148773e-05f; }
inline float feet_to_miles(float in) { return in*0.000189393874739f; }
inline float yards_to_miles(float in) { return in*0.000568183356041f; }
inline float naut_miles_to_miles(float in) { return in*1.15077867312f; }
inline float centimeters_to_miles(float in) { return in*6.21371e-06f; }
inline float millimeters_to_miles(float in) { return in*6.21371e-07f; }
inline float kilometers_to_miles(float in) { return in*0.621371f; }

inline float meters_to_naut_miles(float in) { return in*0.000539957f; }
inline float thou_to_naut_miles(float in) { return in*1.3714900394e-08f; }
inline float inches_to_naut_miles(float in) { return in*1.3714900394e-05f; }
inline float feet_to_naut_miles(float in) { return in*0.000164578888333f; }
inline float yards_to_naut_miles(float in) { return in*0.000493738169914f; }
inline float miles_to_naut_miles(float in) { return in*0.868976827049f; }
inline float centimeters_to_naut_miles(float in) { return in*5.39957e-06f; }
inline float millimeters_to_naut_miles(float in) { return in*5.39957e-07f; }
inline float kilometers_to_naut_miles(float in) { return in*0.539957f; }

inline float meters_to_centimeters(float in) { return in*100.0f; }
inline float thou_to_centimeters(float in) { return in*0.0025399986284f; }
inline float inches_to_centimeters(float in) { return in*2.5399986284f; }
inline float feet_to_centimeters(float in) { return in*30.4799990246f; }
inline float yards_to_centimeters(float in) { return in*91.4402757839f; }
inline float miles_to_centimeters(float in) { return in*160934.449789f; }
inline float naut_miles_to_centimeters(float in) { return in*185199.932587f; }
inline float millimeters_to_centimeters(float in) { return in*0.1f; }
inline float kilometers_to_centimeters(float in) { return in*100000.0f; }

inline float meters_to_millimeters(float in) { return in*1000.0f; }
inline float thou_to_millimeters(float in) { return in*0.025399986284f; }
inline float inches_to_millimeters(float in) { return in*25.399986284f; }
inline float feet_to_millimeters(float in) { return in*304.799990246f; }
inline float yards_to_millimeters(float in) { return in*914.402757839f; }
inline float miles_to_millimeters(float in) { return in*1609344.49789f; }
inline float naut_miles_to_millimeters(float in) { return in*1851999.32587f; }
inline float centimeters_to_millimeters(float in) { return in*10.0f; }
inline float kilometers_to_millimeters(float in) { return in*1000000.0f; }

inline float meters_to_kilometers(float in) { return in*0.001f; }
inline float thou_to_kilometers(float in) { return in*2.5399986284e-08f; }
inline float inches_to_kilometers(float in) { return in*2.5399986284e-05f; }
inline float feet_to_kilometers(float in) { return in*0.000304799990246f; }
inline float yards_to_kilometers(float in) { return in*0.000914402757839f; }
inline float miles_to_kilometers(float in) { return in*1.60934449789f; }
inline float naut_miles_to_kilometers(float in) { return in*1.85199932587f; }
inline float centimeters_to_kilometers(float in) { return in*1e-05f; }
inline float millimeters_to_kilometers(float in) { return in*1e-06f; }


inline float feet_per_second_to_meters_per_second(float in) { return in*0.304799990246f; }
inline float yards_per_second_to_meters_per_second(float in) { return in*0.914402757839f; }
inline float kilometers_per_hour_to_meters_per_second(float in) { return in*0.277777777778f; }
inline float miles_per_hour_to_meters_per_second(float in) { return in*0.447039258988f; }
inline float knots_to_meters_per_second(float in) { return in*0.514445633385f; }

inline float meters_per_second_to_feet_per_second(float in) { return in*3.28084f; }
inline float yards_per_second_to_feet_per_second(float in) { return in*3.00000914403f; }
inline float kilometers_per_hour_to_feet_per_second(float in) { return in*0.911344444444f; }
inline float miles_per_hour_to_feet_per_second(float in) { return in*1.46666428246f; }
inline float knots_to_feet_per_second(float in) { return in*1.68781381184f; }

inline float meters_per_second_to_yards_per_second(float in) { return in*1.09361f; }
inline float feet_per_second_to_yards_per_second(float in) { return in*0.333332317333f; }
inline float kilometers_per_hour_to_yards_per_second(float in) { return in*0.303780555556f; }
inline float miles_per_hour_to_yards_per_second(float in) { return in*0.488886604022f; }
inline float knots_to_yards_per_second(float in) { return in*0.562602889127f; }

inline float meters_per_second_to_kilometers_per_hour(float in) { return in*3.6f; }
inline float feet_per_second_to_kilometers_per_hour(float in) { return in*1.09727996489f; }
inline float yards_per_second_to_kilometers_per_hour(float in) { return in*3.29184992822f; }
inline float miles_per_hour_to_kilometers_per_hour(float in) { return in*1.60934133236f; }
inline float knots_to_kilometers_per_hour(float in) { return in*1.85200428019f; }

inline float meters_per_second_to_miles_per_hour(float in) { return in*2.23694f; }
inline float feet_per_second_to_miles_per_hour(float in) { return in*0.681819290182f; }
inline float yards_per_second_to_miles_per_hour(float in) { return in*2.04546410512f; }
inline float kilometers_per_hour_to_miles_per_hour(float in) { return in*0.621372222222f; }
inline float knots_to_miles_per_hour(float in) { return in*1.15078401515f; }

inline float meters_per_second_to_knots(float in) { return in*1.94384f; }
inline float feet_per_second_to_knots(float in) { return in*0.592482413041f; }
inline float yards_per_second_to_knots(float in) { return in*1.7774526568f; }
inline float kilometers_per_hour_to_knots(float in) { return in*0.539955555556f; }
inline float miles_per_hour_to_knots(float in) { return in*0.868972793191f; }


inline float mpss_to_meters_per_second_per_second(float in) { return in; }
inline float g_to_meters_per_second_per_second(float in) { return in*9.80665002864f; }
inline float feet_per_second_per_second_to_meters_per_second_per_second(float in) { return in*0.304799999537f; }
inline float fpss_to_meters_per_second_per_second(float in) { return in*0.304799999537f; }

inline float meters_per_second_per_second_to_mpss(float in) { return in; }
inline float g_to_mpss(float in) { return in*9.80665002864f; }
inline float feet_per_second_per_second_to_mpss(float in) { return in*0.304799999537f; }
inline float fpss_to_mpss(float in) { return in*0.304799999537f; }

inline float meters_per_second_per_second_to_g(float in) { return in*0.101971621f; }
inline float mpss_to_g(float in) { return in*0.101971621f; }
inline float feet_per_second_per_second_to_g(float in) { return in*0.0310809500336f; }
inline float fpss_to_g(float in) { return in*0.0310809500336f; }

inline float meters_per_second_per_second_to_feet_per_second_per_second(float in) { return in*3.2808399f; }
inline float mpss_to_feet_per_second_per_second(float in) { return in*3.2808399f; }
inline float g_to_feet_per_second_per_second(float in) { return in*32.1740486993f; }
inline float fpss_to_feet_per_second_per_second(float in) { return in; }

inline float meters_per_second_per_second_to_fpss(float in) { return in*3.2808399f; }
inline float mpss_to_fpss(float in) { return in*3.2808399f; }
inline float g_to_fpss(float in) { return in*32.1740486993f; }
inline float feet_per_second_per_second_to_fpss(float in) { return in; }


inline float pounds_to_kilograms(float in) { return in*0.453592909436f; }
inline float ounces_to_kilograms(float in) { return in*0.0283494925441f; }
inline float grams_to_kilograms(float in) { return in*0.001f; }
inline float tons_to_kilograms(float in) { return in*907.185818871f; }
inline float tonnes_to_kilograms(float in) { return in*1000.0f; }
inline float stone_to_kilograms(float in) { return in*6.3502949712f; }

inline float kilograms_to_pounds(float in) { return in*2.20462f; }
inline float ounces_to_pounds(float in) { return in*0.0624998582525f; }
inline float grams_to_pounds(float in) { return in*0.00220462f; }
inline float tons_to_pounds(float in) { return in*2000.0f; }
inline float tonnes_to_pounds(float in) { return in*2204.62f; }
inline float stone_to_pounds(float in) { return in*13.9999872994f; }

inline float kilograms_to_ounces(float in) { return in*35.274f; }
inline float pounds_to_ounces(float in) { return in*16.0000362874f; }
inline float grams_to_ounces(float in) { return in*0.035274f; }
inline float tons_to_ounces(float in) { return in*32000.0725749f; }
inline float tonnes_to_ounces(float in) { return in*35274.0f; }
inline float stone_to_ounces(float in) { return in*224.000304814f; }

inline float kilograms_to_grams(float in) { return in*1000.0f; }
inline float pounds_to_grams(float in) { return in*453.592909436f; }
inline float ounces_to_grams(float in) { return in*28.3494925441f; }
inline float tons_to_grams(float in) { return in*907185.818871f; }
inline float tonnes_to_grams(float in) { return in*1000000.0f; }
inline float stone_to_grams(float in) { return in*6350.2949712f; }

inline float kilograms_to_tons(float in) { return in*0.00110231f; }
inline float pounds_to_tons(float in) { return in*0.0005f; }
inline float ounces_to_tons(float in) { return in*3.12499291263e-05f; }
inline float grams_to_tons(float in) { return in*1.10231e-06f; }
inline float tonnes_to_tons(float in) { return in*1.10231f; }
inline float stone_to_tons(float in) { return in*0.00699999364971f; }

inline float kilograms_to_tonnes(float in) { return in*0.001f; }
inline float pounds_to_tonnes(float in) { return in*0.000453592909436f; }
inline float ounces_to_tonnes(float in) { return in*2.83494925441e-05f; }
inline float grams_to_tonnes(float in) { return in*1e-06f; }
inline float tons_to_tonnes(float in) { return in*0.907185818871f; }
inline float stone_to_tonnes(float in) { return in*0.0063502949712f; }

inline float kilograms_to_stone(float in) { return in*0.157473f; }
inline float pounds_to_stone(float in) { return in*0.0714286362276f; }
inline float ounces_to_stone(float in) { return in*0.00446427963939f; }
inline float grams_to_stone(float in) { return in*0.000157473f; }
inline float tons_to_stone(float in) { return in*142.857272455f; }
inline float tonnes_to_stone(float in) { return in*157.473f; }


inline float millibar_to_pascals(float in) { return in*100.0f; }
inline float bar_to_pascals(float in) { return in*100000.0f; }
inline float inhg_to_pascals(float in) { return in*3386.38672536f; }
inline float inh2o_to_pascals(float in) { return in*248.839784505f; }
inline float meters_of_sea_water_to_pascals(float in) { return in*0.001f; }

inline float pascals_to_millibar(float in) { return in*0.01f; }
inline float bar_to_millibar(float in) { return in*1000.0f; }
inline float inhg_to_millibar(float in) { return in*33.8638672536f; }
inline float inh2o_to_millibar(float in) { return in*2.48839784505f; }
inline float meters_of_sea_water_to_millibar(float in) { return in*1e-05f; }

inline float pascals_to_bar(float in) { return in*1e-05f; }
inline float millibar_to_bar(float in) { return in*0.001f; }
inline float inhg_to_bar(float in) { return in*0.0338638672536f; }
inline float inh2o_to_bar(float in) { return in*0.00248839784505f; }
inline float meters_of_sea_water_to_bar(float in) { return in*1e-08f; }

inline float pascals_to_inhg(float in) { return in*0.0002953f; }
inline float millibar_to_inhg(float in) { return in*0.02953f; }
inline float bar_to_inhg(float in) { return in*29.53f; }
inline float inh2o_to_inhg(float in) { return in*0.0734823883643f; }
inline float meters_of_sea_water_to_inhg(float in) { return in*2.953e-07f; }

inline float pascals_to_inh2o(float in) { return in*0.00401865f; }
inline float millibar_to_inh2o(float in) { return in*0.401865f; }
inline float bar_to_inh2o(float in) { return in*401.865f; }
inline float inhg_to_inh2o(float in) { return in*13.6087030139f; }
inline float meters_of_sea_water_to_inh2o(float in) { return in*4.01865e-06f; }

inline float pascals_to_meters_of_sea_water(float in) { return in*1000.0f; }
inline float millibar_to_meters_of_sea_water(float in) { return in*100000.0f; }
inline float bar_to_meters_of_sea_water(float in) { return in*100000000.0f; }
inline float inhg_to_meters_of_sea_water(float in) { return in*3386386.72536f; }
inline float inh2o_to_meters_of_sea_water(float in) { return in*248839.784505f; }


inline float celsius_to_kelvin(float in) { return in+273.15f; }

inline float kelvin_to_celsius(float in) { return in+-273.15f; }


inline float degrees_to_radians(float in) { return in*0.01745329252f; }
inline float minutes_to_radians(float in) { return in*0.000290888208666f; }

inline float radians_to_degrees(float in) { return in*57.295779513f; }
inline float minutes_to_degrees(float in) { return in*0.0166666666666f; }

inline float radians_to_minutes(float in) { return in*3437.74677079f; }
inline float degrees_to_minutes(float in) { return in*60.0000000001f; }


}

#endif

