/** Generated by ETK Unit Conversion Generator script. */

#ifndef ETK_CONVERSIONS_H
#define ETK_CONVERSIONS_H

namespace etk
{

inline float thou_to_meters(float in) { return in*2.5399986284e-05; }
inline float inches_to_meters(float in) { return in*0.025399986284; }
inline float feet_to_meters(float in) { return in*0.304799990246; }
inline float yards_to_meters(float in) { return in*0.914402757839; }
inline float miles_to_meters(float in) { return in*1609.34449789; }
inline float naut_miles_to_meters(float in) { return in*1851.99932587; }
inline float centimeters_to_meters(float in) { return in*0.01; }
inline float millimeters_to_meters(float in) { return in*0.001; }
inline float kilometers_to_meters(float in) { return in*1000.0; }

inline float meters_to_thou(float in) { return in*39370.1; }
inline float inches_to_thou(float in) { return in*1000.0; }
inline float feet_to_thou(float in) { return in*12000.006096; }
inline float yards_to_thou(float in) { return in*36000.1280164; }
inline float miles_to_thou(float in) { return in*63360053.8165; }
inline float naut_miles_to_thou(float in) { return in*72913398.6595; }
inline float centimeters_to_thou(float in) { return in*393.701; }
inline float millimeters_to_thou(float in) { return in*39.3701; }
inline float kilometers_to_thou(float in) { return in*39370100.0; }

inline float meters_to_inches(float in) { return in*39.3701; }
inline float thou_to_inches(float in) { return in*0.001; }
inline float feet_to_inches(float in) { return in*12.000006096; }
inline float yards_to_inches(float in) { return in*36.0001280164; }
inline float miles_to_inches(float in) { return in*63360.0538165; }
inline float naut_miles_to_inches(float in) { return in*72913.3986595; }
inline float centimeters_to_inches(float in) { return in*0.393701; }
inline float millimeters_to_inches(float in) { return in*0.0393701; }
inline float kilometers_to_inches(float in) { return in*39370.1; }

inline float meters_to_feet(float in) { return in*3.28084; }
inline float thou_to_feet(float in) { return in*8.3333291e-05; }
inline float inches_to_feet(float in) { return in*0.083333291; }
inline float yards_to_feet(float in) { return in*3.00000914403; }
inline float miles_to_feet(float in) { return in*5280.00180247; }
inline float naut_miles_to_feet(float in) { return in*6076.11346829; }
inline float centimeters_to_feet(float in) { return in*0.0328084; }
inline float millimeters_to_feet(float in) { return in*0.00328084; }
inline float kilometers_to_feet(float in) { return in*3280.84; }

inline float meters_to_yards(float in) { return in*1.09361; }
inline float thou_to_yards(float in) { return in*2.77776790001e-05; }
inline float inches_to_yards(float in) { return in*0.0277776790001; }
inline float feet_to_yards(float in) { return in*0.333332317333; }
inline float miles_to_yards(float in) { return in*1759.99523634; }
inline float naut_miles_to_yards(float in) { return in*2025.36498277; }
inline float centimeters_to_yards(float in) { return in*0.0109361; }
inline float millimeters_to_yards(float in) { return in*0.00109361; }
inline float kilometers_to_yards(float in) { return in*1093.61; }

inline float meters_to_miles(float in) { return in*0.000621371; }
inline float thou_to_miles(float in) { return in*1.57828148773e-08; }
inline float inches_to_miles(float in) { return in*1.57828148773e-05; }
inline float feet_to_miles(float in) { return in*0.000189393874739; }
inline float yards_to_miles(float in) { return in*0.000568183356041; }
inline float naut_miles_to_miles(float in) { return in*1.15077867312; }
inline float centimeters_to_miles(float in) { return in*6.21371e-06; }
inline float millimeters_to_miles(float in) { return in*6.21371e-07; }
inline float kilometers_to_miles(float in) { return in*0.621371; }

inline float meters_to_naut_miles(float in) { return in*0.000539957; }
inline float thou_to_naut_miles(float in) { return in*1.3714900394e-08; }
inline float inches_to_naut_miles(float in) { return in*1.3714900394e-05; }
inline float feet_to_naut_miles(float in) { return in*0.000164578888333; }
inline float yards_to_naut_miles(float in) { return in*0.000493738169914; }
inline float miles_to_naut_miles(float in) { return in*0.868976827049; }
inline float centimeters_to_naut_miles(float in) { return in*5.39957e-06; }
inline float millimeters_to_naut_miles(float in) { return in*5.39957e-07; }
inline float kilometers_to_naut_miles(float in) { return in*0.539957; }

inline float meters_to_centimeters(float in) { return in*100.0; }
inline float thou_to_centimeters(float in) { return in*0.0025399986284; }
inline float inches_to_centimeters(float in) { return in*2.5399986284; }
inline float feet_to_centimeters(float in) { return in*30.4799990246; }
inline float yards_to_centimeters(float in) { return in*91.4402757839; }
inline float miles_to_centimeters(float in) { return in*160934.449789; }
inline float naut_miles_to_centimeters(float in) { return in*185199.932587; }
inline float millimeters_to_centimeters(float in) { return in*0.1; }
inline float kilometers_to_centimeters(float in) { return in*100000.0; }

inline float meters_to_millimeters(float in) { return in*1000.0; }
inline float thou_to_millimeters(float in) { return in*0.025399986284; }
inline float inches_to_millimeters(float in) { return in*25.399986284; }
inline float feet_to_millimeters(float in) { return in*304.799990246; }
inline float yards_to_millimeters(float in) { return in*914.402757839; }
inline float miles_to_millimeters(float in) { return in*1609344.49789; }
inline float naut_miles_to_millimeters(float in) { return in*1851999.32587; }
inline float centimeters_to_millimeters(float in) { return in*10.0; }
inline float kilometers_to_millimeters(float in) { return in*1000000.0; }

inline float meters_to_kilometers(float in) { return in*0.001; }
inline float thou_to_kilometers(float in) { return in*2.5399986284e-08; }
inline float inches_to_kilometers(float in) { return in*2.5399986284e-05; }
inline float feet_to_kilometers(float in) { return in*0.000304799990246; }
inline float yards_to_kilometers(float in) { return in*0.000914402757839; }
inline float miles_to_kilometers(float in) { return in*1.60934449789; }
inline float naut_miles_to_kilometers(float in) { return in*1.85199932587; }
inline float centimeters_to_kilometers(float in) { return in*1e-05; }
inline float millimeters_to_kilometers(float in) { return in*1e-06; }


inline float feet_per_second_to_meters_per_second(float in) { return in*0.304799990246; }
inline float yards_per_second_to_meters_per_second(float in) { return in*0.914402757839; }
inline float kilometers_per_hour_to_meters_per_second(float in) { return in*0.277777777778; }
inline float miles_per_hour_to_meters_per_second(float in) { return in*0.447039258988; }
inline float knots_to_meters_per_second(float in) { return in*0.514445633385; }

inline float meters_per_second_to_feet_per_second(float in) { return in*3.28084; }
inline float yards_per_second_to_feet_per_second(float in) { return in*3.00000914403; }
inline float kilometers_per_hour_to_feet_per_second(float in) { return in*0.911344444444; }
inline float miles_per_hour_to_feet_per_second(float in) { return in*1.46666428246; }
inline float knots_to_feet_per_second(float in) { return in*1.68781381184; }

inline float meters_per_second_to_yards_per_second(float in) { return in*1.09361; }
inline float feet_per_second_to_yards_per_second(float in) { return in*0.333332317333; }
inline float kilometers_per_hour_to_yards_per_second(float in) { return in*0.303780555556; }
inline float miles_per_hour_to_yards_per_second(float in) { return in*0.488886604022; }
inline float knots_to_yards_per_second(float in) { return in*0.562602889127; }

inline float meters_per_second_to_kilometers_per_hour(float in) { return in*3.6; }
inline float feet_per_second_to_kilometers_per_hour(float in) { return in*1.09727996489; }
inline float yards_per_second_to_kilometers_per_hour(float in) { return in*3.29184992822; }
inline float miles_per_hour_to_kilometers_per_hour(float in) { return in*1.60934133236; }
inline float knots_to_kilometers_per_hour(float in) { return in*1.85200428019; }

inline float meters_per_second_to_miles_per_hour(float in) { return in*2.23694; }
inline float feet_per_second_to_miles_per_hour(float in) { return in*0.681819290182; }
inline float yards_per_second_to_miles_per_hour(float in) { return in*2.04546410512; }
inline float kilometers_per_hour_to_miles_per_hour(float in) { return in*0.621372222222; }
inline float knots_to_miles_per_hour(float in) { return in*1.15078401515; }

inline float meters_per_second_to_knots(float in) { return in*1.94384; }
inline float feet_per_second_to_knots(float in) { return in*0.592482413041; }
inline float yards_per_second_to_knots(float in) { return in*1.7774526568; }
inline float kilometers_per_hour_to_knots(float in) { return in*0.539955555556; }
inline float miles_per_hour_to_knots(float in) { return in*0.868972793191; }


inline float mpss_to_meters_per_second_per_second(float in) { return in; }
inline float g_to_meters_per_second_per_second(float in) { return in*9.80665002864; }
inline float feet_per_second_per_second_to_meters_per_second_per_second(float in) { return in*0.304799999537; }
inline float fpss_to_meters_per_second_per_second(float in) { return in*0.304799999537; }

inline float meters_per_second_per_second_to_mpss(float in) { return in; }
inline float g_to_mpss(float in) { return in*9.80665002864; }
inline float feet_per_second_per_second_to_mpss(float in) { return in*0.304799999537; }
inline float fpss_to_mpss(float in) { return in*0.304799999537; }

inline float meters_per_second_per_second_to_g(float in) { return in*0.101971621; }
inline float mpss_to_g(float in) { return in*0.101971621; }
inline float feet_per_second_per_second_to_g(float in) { return in*0.0310809500336; }
inline float fpss_to_g(float in) { return in*0.0310809500336; }

inline float meters_per_second_per_second_to_feet_per_second_per_second(float in) { return in*3.2808399; }
inline float mpss_to_feet_per_second_per_second(float in) { return in*3.2808399; }
inline float g_to_feet_per_second_per_second(float in) { return in*32.1740486993; }
inline float fpss_to_feet_per_second_per_second(float in) { return in; }

inline float meters_per_second_per_second_to_fpss(float in) { return in*3.2808399; }
inline float mpss_to_fpss(float in) { return in*3.2808399; }
inline float g_to_fpss(float in) { return in*32.1740486993; }
inline float feet_per_second_per_second_to_fpss(float in) { return in; }


inline float pounds_to_kilograms(float in) { return in*0.453592909436; }
inline float ounces_to_kilograms(float in) { return in*0.0283494925441; }
inline float grams_to_kilograms(float in) { return in*0.001; }
inline float tons_to_kilograms(float in) { return in*907.185818871; }
inline float tonnes_to_kilograms(float in) { return in*1000.0; }
inline float stone_to_kilograms(float in) { return in*6.3502949712; }

inline float kilograms_to_pounds(float in) { return in*2.20462; }
inline float ounces_to_pounds(float in) { return in*0.0624998582525; }
inline float grams_to_pounds(float in) { return in*0.00220462; }
inline float tons_to_pounds(float in) { return in*2000.0; }
inline float tonnes_to_pounds(float in) { return in*2204.62; }
inline float stone_to_pounds(float in) { return in*13.9999872994; }

inline float kilograms_to_ounces(float in) { return in*35.274; }
inline float pounds_to_ounces(float in) { return in*16.0000362874; }
inline float grams_to_ounces(float in) { return in*0.035274; }
inline float tons_to_ounces(float in) { return in*32000.0725749; }
inline float tonnes_to_ounces(float in) { return in*35274.0; }
inline float stone_to_ounces(float in) { return in*224.000304814; }

inline float kilograms_to_grams(float in) { return in*1000.0; }
inline float pounds_to_grams(float in) { return in*453.592909436; }
inline float ounces_to_grams(float in) { return in*28.3494925441; }
inline float tons_to_grams(float in) { return in*907185.818871; }
inline float tonnes_to_grams(float in) { return in*1000000.0; }
inline float stone_to_grams(float in) { return in*6350.2949712; }

inline float kilograms_to_tons(float in) { return in*0.00110231; }
inline float pounds_to_tons(float in) { return in*0.0005; }
inline float ounces_to_tons(float in) { return in*3.12499291263e-05; }
inline float grams_to_tons(float in) { return in*1.10231e-06; }
inline float tonnes_to_tons(float in) { return in*1.10231; }
inline float stone_to_tons(float in) { return in*0.00699999364971; }

inline float kilograms_to_tonnes(float in) { return in*0.001; }
inline float pounds_to_tonnes(float in) { return in*0.000453592909436; }
inline float ounces_to_tonnes(float in) { return in*2.83494925441e-05; }
inline float grams_to_tonnes(float in) { return in*1e-06; }
inline float tons_to_tonnes(float in) { return in*0.907185818871; }
inline float stone_to_tonnes(float in) { return in*0.0063502949712; }

inline float kilograms_to_stone(float in) { return in*0.157473; }
inline float pounds_to_stone(float in) { return in*0.0714286362276; }
inline float ounces_to_stone(float in) { return in*0.00446427963939; }
inline float grams_to_stone(float in) { return in*0.000157473; }
inline float tons_to_stone(float in) { return in*142.857272455; }
inline float tonnes_to_stone(float in) { return in*157.473; }


inline float millibar_to_pascals(float in) { return in*100.0; }
inline float bar_to_pascals(float in) { return in*100000.0; }
inline float inhg_to_pascals(float in) { return in*3386.38672536; }
inline float inh2o_to_pascals(float in) { return in*248.839784505; }
inline float meters_of_sea_water_to_pascals(float in) { return in*0.001; }

inline float pascals_to_millibar(float in) { return in*0.01; }
inline float bar_to_millibar(float in) { return in*1000.0; }
inline float inhg_to_millibar(float in) { return in*33.8638672536; }
inline float inh2o_to_millibar(float in) { return in*2.48839784505; }
inline float meters_of_sea_water_to_millibar(float in) { return in*1e-05; }

inline float pascals_to_bar(float in) { return in*1e-05; }
inline float millibar_to_bar(float in) { return in*0.001; }
inline float inhg_to_bar(float in) { return in*0.0338638672536; }
inline float inh2o_to_bar(float in) { return in*0.00248839784505; }
inline float meters_of_sea_water_to_bar(float in) { return in*1e-08; }

inline float pascals_to_inhg(float in) { return in*0.0002953; }
inline float millibar_to_inhg(float in) { return in*0.02953; }
inline float bar_to_inhg(float in) { return in*29.53; }
inline float inh2o_to_inhg(float in) { return in*0.0734823883643; }
inline float meters_of_sea_water_to_inhg(float in) { return in*2.953e-07; }

inline float pascals_to_inh2o(float in) { return in*0.00401865; }
inline float millibar_to_inh2o(float in) { return in*0.401865; }
inline float bar_to_inh2o(float in) { return in*401.865; }
inline float inhg_to_inh2o(float in) { return in*13.6087030139; }
inline float meters_of_sea_water_to_inh2o(float in) { return in*4.01865e-06; }

inline float pascals_to_meters_of_sea_water(float in) { return in*1000.0; }
inline float millibar_to_meters_of_sea_water(float in) { return in*100000.0; }
inline float bar_to_meters_of_sea_water(float in) { return in*100000000.0; }
inline float inhg_to_meters_of_sea_water(float in) { return in*3386386.72536; }
inline float inh2o_to_meters_of_sea_water(float in) { return in*248839.784505; }


inline float celsius_to_kelvin(float in) { return in+273.15; }

inline float kelvin_to_celsius(float in) { return in+-273.15; }


inline float degrees_to_radians(float in) { return in*0.0174532862793; }
inline float minutes_to_radians(float in) { return in*0.000290887935423; }

inline float radians_to_degrees(float in) { return in*57.2958; }
inline float minutes_to_degrees(float in) { return in*0.0166666569704; }

inline float radians_to_minutes(float in) { return in*3437.75; }
inline float degrees_to_minutes(float in) { return in*60.0000349066; }


}

#endif

